name: Deploy to Turhost via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: kozalisveris.com
        username: kozalisv
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/kozalisv/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/.github/**
          **/.vs/**
          **/.DS_Store
          .ftp-deploy-sync-state.json
          **/node_modules/**
          package.json
          package-lock.json
          firebase.json
          .firebaserc
          functions/**
          scss/**
          src/**
          google-sheets-cache/**
          import-products.js
          data-harytlar.js
          README.md
