name: Deploy to Turhost via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: kozalisveris.com
        port: 22
        username: kozalisv
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: ./*
        remote_path: /home/kozalisv/public_html
        sftp_only: true
